# Generated by Django 4.0 on 2022-06-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museo', '0010_expose_correct date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(check=models.Q(valor__gt=0), name='valor constraint'),
        ),
    ]
